plugins:
  - "@trivago/prettier-plugin-sort-imports"
printWidth: 120

overrides:
  - files: "*.md"
    options:
      proseWrap: "always"
  - files: ["*.ts", "*.tsx"]
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
      parser: "typescript"
